### ISSUE TITLE
How to build the custom Xbian Image 

### ISSUE THREAD

**Issue by amanharitsh123** [xbianonpi/xbian#857]
I have made some changes to the kodi fork https://github.com/amanharitsh123/xbmc  . I want to make a custom xbian image using this fork and want to test my changes. How can i do this ?
Please Help

**Comment by mkreisl** [comment]
@amanharitsh123 

Do you have already built Kodi from your source? If you did it, you do not need to build an XBian image, it's just enough to install your custum kodi deb package (xbian-package-xbmc) via dpkg -i

If you still have to build your own kodi package, please read an follow these instructions: https://github.com/xbianonpi/xbian/wiki/Building-XBian-packages

**Comment by amanharitsh123** [comment]
@mkreisl 
Thanks for the reply 
I want to build kodi isengard from source https://github.com/amanharitsh123/xbmc
How can i make deb package using my repo(https://github.com/amanharitsh123/xbmc)
Can you please help?

**Comment by amanharitsh123** [comment]
and after building a deb package , can i directly install that on my rpi running xbian ?
Should i have to remove the kodi that  my xbian image already had ?
@mkreis

**Comment by mkreisl** [comment]
Ah, ok.

Step 1:
Please read an follow these instructions: https://github.com/xbianonpi/xbian/wiki/Building-XBian-packages. This installs XBian development environment

Step 2:
You have to clone this repository: https://github.com/xbianonpi/xbian-package-xbmc
This is the repository to build Kodi

Step 3:
You need our `treeIsengard` tree from here https://github.com/xbianonpi/xbian-sources-xbmc, because there are many patches to make it work under XBian. So you have to fork it and make your own changes in `treeIsengard' branch

Step 4
Assuming you want to build package for Pi 2/3, you have to modify the `config_source_addr` setting in this file https://github.com/xbianonpi/xbian-package-xbmc/blob/master/build/rpi2-cross-isengard/config (has to point to your forked and modified repo)

Step 5:
To build package, you have to run $xbiangit --arch rpi2-cross-isengard

Please note that Kodi Isengard is very very out of date, so I can not guarantee that building of this version still works

**Comment by mkreisl** [comment]
> and after building a deb package , can i directly install that on my rpi running xbian ?
Yes

> Should i have to remove the kodi that my xbian image already had ?
No

**Comment by amanharitsh123** [comment]
@mkreisl Thanks a lot 
Its really a great help to me

**Comment by amanharitsh123** [comment]
With the development setup guide , https://github.com/xbianonpi/xbian/wiki/Building-XBian-packages
It doesnt found any command "xbiangit"

**Comment by mkreisl** [comment]
You have to log out and log in again

The command is `$xbiangit`

**Comment by amanharitsh123** [comment]
Tried that , looks like i have to add the path to $PATH

**Comment by mkreisl** [comment]
$xbiangit is not a command, it's a environment variable and points to run.me

**Comment by amanharitsh123** [comment]
it means that echo $xbiangit must return some path then?

**Comment by amanharitsh123** [comment]
i did a chmod 777 /etc/profile.d/xbiangit.sh , it solved the issue

**Comment by mkreisl** [comment]
> it means that echo $xbiangit must return some path then?

Exactly

**Comment by mkreisl** [comment]
> i did a chmod 777 /etc/profile.d/xbiangit.sh , it solved the issue

Hmm, thats weird:

```
manfred@kmnote5:/usr/src/xbian/xbian-package-kernel> ll /etc/profile.d/xbiangit.sh 
-rw-r--r-- 1 root root 273  1. Mai 2017  /etc/profile.d/xbiangit.sh
```

**Comment by amanharitsh123** [comment]
No , there is something wrong . Let me check

**Comment by amanharitsh123** [comment]
I have found the issue , we cant run $xbiangit with the root user. After loggin in again , we have to continue the build process through as a user , not root

**Comment by mkreisl** [comment]
Ehm, working under root is usually never a good idea :smile:

**Comment by amanharitsh123** [comment]
i think there is a typo here "cd ../xbian-prep-root; $xbiangit --arch [platform] --action build" , shouldnt it be the "cd . " rather than "cd .."

https://github.com/xbianonpi/xbian/wiki/Building-XBian-packages
Step 4

**Comment by mkreisl** [comment]
No, that command installs your schroot build environment. You need this for building binary packages.
Btw, XBian usually does not use a cross compiler (expect building kernel packages)

**Comment by amanharitsh123** [comment]
and i there is this error now 
after running $xbiangit --arch [platform] --action build
/create.buildroot no such file or directory

**Comment by mkreisl** [comment]
```
$xbiangit --arch amd64stretch --action build
```

**Comment by amanharitsh123** [comment]
same error , I am using ubuntu 16.04

**Comment by mkreisl** [comment]
Hmmm, I have run that command many many times, never had issues. I'm running Debian Stretch for doing that

**Comment by amanharitsh123** [comment]
then let me try that on my debian vm

**Comment by mkreisl** [comment]
But make sure that you are root when running that command

**Comment by amanharitsh123** [comment]
"cd ../xbian-prep-root; $xbiangit --arch [platform] --action build
 in this command , we are in the this directory https://github.com/xbianonpi/xbian/tree/master/xbian-prep-root
 right ?

**Comment by mkreisl** [comment]
we are in xbian-prep-root folder, right

**Comment by amanharitsh123** [comment]
@mkreisl  the same error on debian jessie

**Comment by mkreisl** [comment]
Hmmm, looks like your XBIANROOT variable has not been set properly

```
root@kmnote5-debian9:/usr/src/xbian/xbian-prep-root/extra-files# env | grep XBIAN
XBIANROOT=/usr/src/xbian
```

**Comment by amanharitsh123** [comment]
should i clone this in /usr/src/

**Comment by amanharitsh123** [comment]
XBIANROOT is set correctly , i have checked

**Comment by mkreisl** [comment]
> should i clone this in /usr/src/

No, you can do this in your home directory

**Comment by mkreisl** [comment]
Hmmm, at the moment I'm a bit confused. I think you're making an error but do not know what the error is

**Comment by amanharitsh123** [comment]
Can you guess some possible error ?
Looks like the script is referring to a wrong directory for create.buildroot which is present in the parent of current working directory

**Comment by mkreisl** [comment]
Haven't set up this enviromnent for a long time.

Please give me some time to install it on a fresh environment

**Comment by mkreisl** [comment]
... and the build root procedure is broken at the moment due to some deb packages could not be found.

Have to fix this first

**Comment by amanharitsh123** [comment]
oh alright , Thank you
please let me know if you find any fix :)

**Comment by amanharitsh123** [comment]
Fix : sudo -E $xbiangit --arch [platform] --action build

**Comment by mkreisl** [comment]
I have commited some fixes, https://github.com/xbianonpi/xbian/commit/80feea4a37416346c2b2300c4ac612a65bf58e90, https://github.com/xbianonpi/xbian/commit/4d3b20ff21771bdfe045fd76c2a340c8e289d9c7, https://github.com/xbianonpi/xbian-package-repo/commit/b2b64de561aeacae67078ffbd79e9cb4d47ce67a

and updated wiki article https://github.com/xbianonpi/xbian/wiki/Building-XBian-packages

Now it should work without issues

Please note, the user has to be member of group `users`. If you don't want this, you have to edit
config files in `/etc/schroot/chroot.d` folder manually

**Comment by amanharitsh123** [comment]
@mkreisl  Thanks a lot for the help :)

**Comment by amanharitsh123** [comment]
I am gettting some error https://paste.fedoraproject.org/paste/8ir9TzMrLwM94OmgJEGo~A
after sudo -E $xbiangit --action build

**Comment by mkreisl** [comment]
Hmmm, never get this issue, looks like that another process is accessing this folder. 

Probably not good idea to use `/home/osboxes/Desktop/XFS/xbian` as path, isn't Desktop your current desktop?

I think better path is /home/osboxes/Desktop

**Comment by amanharitsh123** [comment]
and on ubuntu system is , 
Method gave invalid 103 redirect message after 20 mins

**Comment by mkreisl** [comment]
Sorry, at this point I have no idea how to help.
I'm using openSUSE 13.1 (my local devel system), Debian Jessie (this is our main build system), Debian Stretch (VM for testing and ARM powered home server), never had this issue

Are any FS mounted by autofs?

**Comment by amanharitsh123** [comment]
Probably not , I think this erro Method gave invalid 103 redirect messageis due to some broken ppa 
this happens while apt update checking for ftps

**Comment by mkreisl** [comment]
Do you really run `sudo -E $xbiangit --action build`?
Why do you omit parameter --arch paramater

**Comment by amanharitsh123** [comment]
Because i was not sure which one to choose for rpi3

**Comment by mkreisl** [comment]
In your case **amd64stretch** is the best choice

I already mentioned this:

> Current Debian is Stretch, so you have to install amd64stretch root environment if you want to build Kodi package for Pi 2/3

**Comment by amanharitsh123** [comment]
Well , i have something in my mind . 
i think emdebian.org doesnt contain armhf packages
for debian jessie 
we can add this as a mirror http://ftp.debian.org/debian/dists/jessie/main/binary-armhf/
But i dont know where to make changes

**Comment by mkreisl** [comment]
emdebian.org supplies multiarch support (incl. cross compiler) for Debian Jessie, but this is not required for Debian Stretch, because Stretch comes with complete multiarch support already included.
And, you do not need to add anything as mirror

**Comment by amanharitsh123** [comment]
@mkreisl  I badly need to compile  kodi-isengard which cant be done using stretch and debian chroot is ubale to apt-update from emdebian 
Is there anything i can do right now ?

**Comment by mkreisl** [comment]
> I badly need to compile kodi-isengard which cant be done using stretch

Why - error messages?

Did you have sucessfully set up root environment **amd64stretch**?

And of course, you have to edit file `.../xbian-package/xbmc/build/rpi2-cross-isengard/config`, like this

```
...
config_build_env=schroot -c amd64stretch -p --
config_source_branch=treeIsengard
config_source_addr=https://github.com/xbianonpi/xbian-sources-xbmc.git
...

**Comment by amanharitsh123** [comment]
I have done that , now there is a error for 
no rule to make target 'java-not-found ', needed by 'codegenerator'

**Comment by mkreisl** [comment]
Hmmm, so seems that Isengard can not be build for Debian Stretch. I was trying it also, and my build stopped during configure process (havent looked deeper, does not make sense for me).

So, I'm currently building Isengard for Debian Jessie, that seems to work. But, unfortunately setting up root (amd64jessie) fails (got same Method gave invalid 103 redirect message errors), but I have already fixed that

You can apply the fix and locally try to setup amd64jessie again
```
manfred@kmnote5-debian9:/usr/src/xbian$ git diff create.buildroot
diff --git a/create.buildroot b/create.buildroot
index ea62cbb..42abad8 100644
--- a/create.buildroot
+++ b/create.buildroot
@@ -165,7 +165,7 @@ do_other()
     esac
     LC_ALL=C schroot --directory / -p -c $config_platform -- apt-get update 2>/dev/null || ( \
         case "$config_platform" in
-            *stretch*)
+            *stretch*|*jessie*)
                 # As it was written (for Debian Stretch) apt-get does not work with method mirror://
                 schroot --directory / -c $config_platform -p -- sed -i -e 's%mirror://apt.xbian.org/mirror.txt%http://apt.xbian.org/%g' /etc/apt/sources.list.d/xbian.list
  ```

Seems to work, but Isengard is not compatible with libcec4 library. Before building, libcec4 has to be removed and libcec3 installed manually in root amd64jessie

**Comment by amanharitsh123** [comment]
Which Linux distro are you using ? 
I am still getting this error Method gave invalid 103 redirect message  after 
sudo -E $xbiangit --arch amd64jessie --action build

**Comment by mkreisl** [comment]
Debian 9 VM for testing, fresh setup of amd64jessie root.

You have to remove amd64jessie folder (sudo -E $XBIANROOT/build-root-dirs/amd64jessie) and setup root amd64jessie again. Did you do that?

**Comment by amanharitsh123** [comment]
Yes , I did that . but still the error with 
GET ftp.de.debian.org jessie/main/amd64 packages

**Comment by amanharitsh123** [comment]
Thw same error if i try to apt-get update in schroot

**Comment by mkreisl** [comment]
Please show me file /etc/apt/sources.list.d/xbian.list

**Comment by amanharitsh123** [comment]
https://paste.fedoraproject.org/paste/OVq7hdszRR7uei2EQ-HoFw

**Comment by amanharitsh123** [comment]
https://paste.fedoraproject.org/paste/2eaOfI-5ZbC~JyNtE92LBQ

**Comment by mkreisl** [comment]
That's the culprit: mirror://apt.xbian.org/mirror.txt

Either my fix does not work for you, or you did not applied this fix correctly or you did not set up root again

It must be http://apt.xbian.org

**Comment by amanharitsh123** [comment]
Well , I have cloned a fresh repo again. Is there any thing else i should do?

**Comment by amanharitsh123** [comment]
I can edit the /etc/apt/sources.list.d/xbian.list , may be then i can do a apt-get  update

**Comment by mkreisl** [comment]
> I can edit the /etc/apt/sources.list.d/xbian.list , may be then i can do a apt-get update

Yeah, that would be possible. And after done that, you have to continue by running
`sudo -E $xbiangit --arch amd64jessie --action other`. But if the script does not work correctly, you will fell in the same error again

**Comment by amanharitsh123** [comment]
Dependency error , libc64:amd64
multiarch support
after running sudo -E $xbiangit --arch amd64jessie --action other

**Comment by mkreisl** [comment]
Hmmm, sorry. There is something absolutely wrong with your installation. Or maybe we're talking about different things

**Comment by amanharitsh123** [comment]
Well , for the last time . What is the complete installation procedure that worked for u?

**Comment by mkreisl** [comment]
I'll do it again and post log here

**Comment by mkreisl** [comment]
I'm going crazy. Yesterday it works flawlessly, today this stupid error is back again.

Have to look what's going on today

**Comment by mkreisl** [comment]
So, finally it should work after that fix: https://github.com/xbianonpi/xbian/commit/54bc2cf45bd7220b4a28eff5ca1d74ccbc5763aa

Here is my log: http://paste.ubuntu.com/p/PXR2sFgYW2/

hth

**Comment by amanharitsh123** [comment]
Trying :)

**Comment by mkreisl** [comment]
Fine, so don't forget to install libcec3 before building Kodi Isengard

**Comment by amanharitsh123** [comment]
Thanks :) 
I have done that , build in progress . Lets see what happens next  :)

**Comment by amanharitsh123** [comment]
At the time of compiling rpi-isengard , i had this error https://paste.fedoraproject.org/paste/zZV7Yor~FOYJ87w8EEbykw
looks like i need to update automake to 1.15.1

**Comment by mkreisl** [comment]
I don't think so, because build process is building it's own autoconf/automake, see here https://github.com/xbianonpi/xbian-package-xbmc/blob/master/hooks.d/pre-configure.d/00-pre-depends#L18

**Comment by amanharitsh123** [comment]
@mkreisl Then may be I should replace the automake in the /tools/native with the latest one

**Comment by mkreisl** [comment]
> @mkreisl Then may be I should replace the automake in the /tools/native with the latest one

No, that version **must** work.

I assume that this issue is caused by another problem. As already told, yesterday I was building Isengard without any issue on my Debian Stretch VM
At the moment, I'm building Isengard on my older Debian Jessie VM (I found small (CEC related) issue again, but this has nothing to do with your problem)
And at least, I'm setting up build enviromnent on my stone old Ubuntu 14.04 VM, will see how it works there

**Comment by amanharitsh123** [comment]
@mkreisl  Please let me know the results :) 
Currently i am setting up the debian 9 vm , lets see if i can build on that

**Comment by mkreisl** [comment]
Sure, I will do :smile:
Debian 8 VM --> built ok

**Comment by amanharitsh123** [comment]
.deb created successfully ?

**Comment by mkreisl** [comment]
> .deb created successfully ?

Yes (Debian 8 VM)

**Comment by amanharitsh123** [comment]
Can you provide the logs ?

**Comment by mkreisl** [comment]
Too late, already removed xbian-package-xbmc folder. Sorry

**Comment by mkreisl** [comment]
It seems that build on Ubuntu 14.04 fails (auto<whatever> issue)
Running apt-get upgrade to see if that makes any difference

**Comment by mkreisl** [comment]
Yep, after installing some additional packages (autopoint, openjdj-7-jre-headless, swig, doxygen, g++) build process ( sudo -E $xbiangit --arch rpi2-cross-isengard --action wipe,build) is running

**Comment by mkreisl** [comment]
All testbuilds completed successfully (Debian Stretch, Debian Jessie, Ubuntu 14.04 LTS)

Here you can find my 14.04 build log of sudo -E $xbiangit --arch rpi2-cross-isengard --action wipe,build: http://paste.ubuntu.com/p/TFmJXRt6Yp/
and here is my complete 14.04 package list http://paste.ubuntu.com/p/Qj785RMCVg/

hth

**Comment by mkreisl** [comment]
> Have you downgraded the libcec every time?

Sure, I did. It's necessary

Oh, I forgot to post final libcec fix inside of schroot. You have to copy libcec.pc

```
cp /usr/lib/pkgconfig/libcec.pc  /usr/lib/arm-linux-gnueabihf/pkgconfig/
```

**Comment by amanharitsh123** [comment]
After building i have two deb packages
should i install both packages simply using dpkg -i *.deb on my rpi?

**Comment by mkreisl** [comment]
> After building i have two deb packages
> should i install both packages simply using dpkg -i *.deb on my rpi?

No, you need only one, the smaller one. The second holds debug information only

**Comment by amanharitsh123** [comment]
Xbian image already has kodi Krypton , should I remove that before installing?

**Comment by mkreisl** [comment]
> Xbian image already has kodi Krypton , should I remove that before installing?

You already asked that, and I was answering: NO

**Comment by amanharitsh123** [comment]
Thanks :)

**Comment by mkreisl** [comment]
> Thanks :)

But you have to consider, that you're building your package for Debian Jessie, so you have to install this package on a Debian Jessie XBian installation.

**Comment by amanharitsh123** [comment]
and where can i find xbian jessie image

**Comment by mkreisl** [comment]
There is at least one available for download

https://sourceforge.net/projects/xbian/files/release/XBian_Jessie_latest_rpi3.img.gz/download

**Comment by amanharitsh123** [comment]
Ok , trying to install deb 
Hope i will not face any dependencies issues :)

**Comment by mkreisl** [comment]
> Hope i will not face any dependencies issues :)

I suppose you'll have to downgrade libcec packags there

**Comment by amanharitsh123** [comment]
Dependencies Errors 
`Preparing to unpack xbian-package-xbmc15.2-1520517510.deb ...
Unpacking xbian-package-xbmc (15.2-1520517510) over (17.3-1496270252) ...
dpkg: dependency problems prevent configuration of xbian-package-xbmc:
 xbian-package-xbmc depends on libjasper1; however:
  Package libjasper1 is not installed.
 xbian-package-xbmc depends on libgif4; however:
  Package libgif4 is not installed.
 xbian-package-xbmc depends on libplist3; however:
  Package libplist3 is not installed.
 xbian-package-xbmc depends on libnfs8; however:
  Package libnfs8 is not installed.
 xbian-package-xbmc depends on alsa-base; however:
  Package alsa-base is not installed.
 xbian-package-xbmc depends on libpng16-16; however:
  Package libpng16-16 is not installed.
 xbian-package-xbmc depends on libjasper1; however:
  Package libjasper1 is not installed.`

**Comment by mkreisl** [comment]
Run `sudo apt-get install -f`

**Comment by amanharitsh123** [comment]
That overwrites the kodi 17 over 15 again

**Comment by mkreisl** [comment]
Are you really running Debian Jessie ???

AFAIR libpng16-16, libnfs8 is part of Stretch **and** not Part of Jessie

**Comment by amanharitsh123** [comment]
Yes I am running Debian jessie 
IF libpng16-16, libnfs8 is part of Stretch then why isengard cross compiled in amd64jessie depends on these packages :(

**Comment by mkreisl** [comment]
Look at your dependencies in deb file you built
`dpkg-deb -I dpkg-deb -I xbian-package-xbmc15.2-xxxxxxxxx.deb`
And please learn a bit more about debian package and their dependencies
This is not a tutorial here, sorry

**Comment by mkreisl** [comment]
I've absolutely no idea where the dependency libnfs8 came from. Isengard has libnfs4 as dependency configured, libnfs4 is installed in amd64jessie root, and package built has libnfs8 as dependency.
You have to figure out where that came from

**Comment by amanharitsh123** [comment]
Thats , what i am thinking right now :|

**Comment by amanharitsh123** [comment]
Do you have any isengard .deb package ?

**Comment by mkreisl** [comment]
Yeah, that's extremly strange
kodi.bin has libnfs.4.so as dependency, so why does debhelper put libnfs8 as depedency in and ignores hardcoded libnfs4 dep?
And, I was looking into package built on Debian Jessie machine, its exactly the same, libnfs8 as dependency

**Comment by mkreisl** [comment]
> Do you have any isengard .deb package ?

I looked into my local deb package built Nov 2015, there is libnfs4 as dependency

**Comment by amanharitsh123** [comment]
Thats Strange :|

**Comment by mkreisl** [comment]
I'm running next test (I want to know what's going on)
I'm using my old amd64jessie root and build package against this one
Will see what happens.

**Comment by amanharitsh123** [comment]
@mkreisl  Should i try installation on some old distro like ubuntu 14?

**Comment by mkreisl** [comment]
> @mkreisl Should i try building on some old distro like ubuntu 14?

Installation of what?

**Comment by amanharitsh123** [comment]
@mkreisl building*

**Comment by mkreisl** [comment]
That has nothing do do with host os, must be inside of schroot

**Comment by amanharitsh123** [comment]
I have noticed that libnfs4 isnt installed in jessie schroot.

**Comment by mkreisl** [comment]
> I have noticed that libnfs4 isnt installed in jessie schroot.

It is, because if not build fails

**Comment by mkreisl** [comment]
I gave up, have no idea where that strange dependencies came from

Now, escape to the front is the strategy:

Currently building Isengard for Stretch (libjasper-dev:armhf and libcec3 has been picked from Jessie repos) and see what happens.

And that version - if built is successful - can installed here on my Pi3

**Comment by mkreisl** [comment]
Build failed, source is not compatible with gcc 6.3

So, before I can not sleep tonight, I was installing XBian Debian Jessie image, modified config file:
```
manfred@kmnote5-debian9:/usr/src/xbian/xbian-package-xbmc$ git diff
diff --git a/build/rpi2-cross-isengard/config b/build/rpi2-cross-isengard/config
index 6fbdcd1..0262a6a 100644
--- a/build/rpi2-cross-isengard/config
+++ b/build/rpi2-cross-isengard/config
@@ -6,5 +6,5 @@ config_deb_pkgname=xbian-package-xbmc
 config_deb_ctrlextra=Breaks: xbian-package-xbmc-gotham-nightly (<<3.0.0~)
 config_source_reset=no
 config_source_refresh=yes
-config_deb_depends=\${shlibs:Depends}, libgif4, consolekit, udisks2, upower, xbian-package-config-xbmc, libplist2, libnfs4, libass5, libsdl-image1.2, libssh-4, librtmp1, udisks, libpulse0, libmpeg2-4, libxslt1.1, xbian-package-xbianhome, xbian-package-xbmc-scripts (>= 1.1.0), alsa-base, alsa-tools, libbluetooth3, libcec (>=3.0.1), libmad0, libtiff5, libafpclient0, python-sqlite, libmysqlclient18, libtinyxml2.6.2, libyajl2, liblzo2-2, libpython2.7, libpcrecpp0, libcdio13, libsamplerate0, libsmbclient, libpng12-0, libaacs0, libbluray1, libenca0, libfontconfig1, libjasper1, ttf-dejavu-core, libvorbisfile3, libcurl3-gnutls, xbian-package-firmware (>=2.6.0)
+config_deb_depends=\${shlibs:Depends}, libgif4, consolekit, udisks2, upower, xbian-package-config-xbmc, libass5, libsdl-image1.2, libssh-4, librtmp1, udisks, libpulse0, libmpeg2-4, libxslt1.1, xbian-package-xbianhome, xbian-package-xbmc-scripts (>= 1.1.0), alsa-base, alsa-tools, libbluetooth3, libcec (>=3.0.1), libmad0, libtiff5, libafpclient0, python-sqlite, libmysqlclient18, libtinyxml2.6.2, libyajl2, liblzo2-2, libpython2.7, libpcrecpp0, libcdio13, libsamplerate0, libsmbclient, libpng12-0, libaacs0, libbluray1, libenca0, libfontconfig1, libjasper1, ttf-dejavu-core, libvorbisfile3, libcurl3-gnutls, xbian-package-firmware (>=2.6.0)
 config_build_addons=
```

built new Kodi Isengard package,
added stretch to /etc/apt/sources.list
```
root@xbian:/mnt# cat /etc/apt/sources.list
deb http://http.debian.net/debian jessie main non-free
deb http://http.debian.net/debian stretch main non-free

```

 and installed missing packages

```
sudo apt-get install libjasper1 libgif4 alsa-base libpng16-16
```

Now everything looks ok and Kodi 15.2 comes up

hth

**Comment by amanharitsh123** [comment]
@mkreisl Thanks a lot , Your guidance has cleared many of my concepts regarding cross compilation , schroot and debian packages . 
I will try your suggested fix soon , Thank you :)

**Comment by mkreisl** [comment]
:exclamation:  Last but not least, I found the reason for that strange behavior :exclamation: 

You have to edit config file `xbian/config`, and change **stretch** to **jessie** (2x).

The old configuration `xbian-package-xbmc/build/rpi2-cross-isengard/config` has not been updated from **config_build_env=schroot -c cross -p --** to **config_build_env=schroot -c amd64${config_os_version} -p --** but the hook script `xbian-package-xbmc/hooks.d/pre-deb.d/fix-dependencies` requires this

So, after editing xbian/config, it is enough to build Isengard package again by **$xbiangit --arch rpi2-cross-isengard --action install,deb**, no recompiling necessary

But, nevertheless, I suppose, you'll have to install missing packages manually

**Comment by amanharitsh123** [comment]
@mkreisl Thank You for the Suggestion 
I have successfully build the package by changing the config_deb_depends and manually installing some dependencies . Although some cec error occured after installing deb package which was fixed by reinstalling libcec on xbian . Everthing seems to work fine now .

Thanks a lot @mkreisl  I have got some idea about the xbian project now and i look forward to  contribute to this project in the future. Thanks You :)

**Comment by mkreisl** [comment]
> Although some cec error occured after installing deb package, that I fixed by

Yeah, that was to be expected, because latest Jessie image has libcec4 installed, and we know that Isengard is built against libcec3


> I have got some idea about the xbian project now and look forward to contribute to this project in the future

Nice to hear :smile: Thanks for your response
